language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 4c92132f45d2eff9628981bc7e16a8f80591e19b 
  keep_history: true
  on:
    branch: master